### ISSUE TITLE
Gzipped input

### ISSUE THREAD

**Issue by PotapenkoEugene** [simonorozcoarias/TIP_finder#4]
Hi
Is there possible to run this great tool on .fastq.gz?
I have about 300 samples of big Barley genomes. It's almost impossible to unpack all of it on server.

I got this error:
FATAL ERROR processing 15_18: forward read file does not have the correct extension (fastq or fq). Exiting

If not: 
Is it possible to summarize results of different runs, if i will work with batches of size 10 for example.

I will be very grateful for any help. Thank you again for great tool!

**Comment by simonorozcoarias** [comment]
Hi, Sadly TIP_finder can't use compress file (like .gz). It needs fastq format file in order to split the reads and to execute the processes in parallel.

But you can use TIP_finder in batches (as you suggested), then TIP_finder will create one output file for each genome. Finally, you must copy all the outputs in a single folder. 

Remember to execute TIP_finder_utils with the final folder (with the all results from all batches) in order to get the final matrix and the rest of intesting data.

Thank you for using TIP_finder and happy new year!!

**Comment by PotapenkoEugene** [comment]
Many thanks for your answer!

I will try to do it in batches! 

Happy New Year!
